### PR TITLE
Add wip cloudtrail

### PR DESCRIPTION
**Pull request by waltervargas**

### CODE REVIEW

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
comment from samless notificator

**Comment by waltervargas** [comment]
hola, this is a comment

**Comment by waltervargas** [comment]
hola, this is a comment

**Comment by waltervargas** [comment]
hola, this is a comment
 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

```this is a 
 block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
hola, this is a comment

 ```this is a block of code```

**Comment by waltervargas** [comment]
[samless] Apply Results: OK

**Comment by waltervargas** [comment]
[samless] Apply Results: OK

**Comment by waltervargas** [comment]
[samless] Apply Errors: ...

**Comment by waltervargas** [comment]
[samless] Apply Errors: ...

**Comment by waltervargas** [comment]
[samless] Apply Errors: ...

**Comment by waltervargas** [comment]
[samless] User alex.dupuy updated.

**Comment by waltervargas** [comment]
[samless] User alberto.rojas updated.

**Comment by dupuy26** [comment]
[samless] User alberto.rojas updated.

**Comment by dupuy26** [comment]
[samless] User alberto.rojas updated.

**Comment by dupuy26** [comment]
[samless] User alberto.rojas updated.

**Comment by dupuy26** [comment]
[samless] User alberto.rojas updated.

**Pull request closed without merging**
